//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.pm.transactionprocessor.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.pm.transactionprocessor.soap package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.pm.transactionprocessor.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateTransactionRequest }
     * 
     * @return
     *     the new instance of {@link CreateTransactionRequest }
     */
    public CreateTransactionRequest createCreateTransactionRequest() {
        return new CreateTransactionRequest();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse }
     * 
     * @return
     *     the new instance of {@link CreateTransactionResponse }
     */
    public CreateTransactionResponse createCreateTransactionResponse() {
        return new CreateTransactionResponse();
    }

    /**
     * Create an instance of {@link CorrectTransactionRequest }
     * 
     * @return
     *     the new instance of {@link CorrectTransactionRequest }
     */
    public CorrectTransactionRequest createCorrectTransactionRequest() {
        return new CorrectTransactionRequest();
    }

    /**
     * Create an instance of {@link CorrectTransactionResponse }
     * 
     * @return
     *     the new instance of {@link CorrectTransactionResponse }
     */
    public CorrectTransactionResponse createCorrectTransactionResponse() {
        return new CorrectTransactionResponse();
    }

}
